# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sim(object):
    def setupUi(self, Sim):
        Sim.setObjectName("Sim")
        Sim.resize(283, 427)
        self.amountBotsSlider = QtWidgets.QSlider(Sim)
        self.amountBotsSlider.setGeometry(QtCore.QRect(50, 240, 160, 22))
        self.amountBotsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.amountBotsSlider.setObjectName("amountBotsSlider")
        self.label_2 = QtWidgets.QLabel(Sim)
        self.label_2.setGeometry(QtCore.QRect(50, 218, 165, 16))
        self.label_2.setObjectName("label_2")
        self.amountBotsSlider_2 = QtWidgets.QSlider(Sim)
        self.amountBotsSlider_2.setGeometry(QtCore.QRect(46, 102, 160, 22))
        self.amountBotsSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.amountBotsSlider_2.setObjectName("amountBotsSlider_2")
        self.label_3 = QtWidgets.QLabel(Sim)
        self.label_3.setGeometry(QtCore.QRect(46, 80, 165, 16))
        self.label_3.setObjectName("label_3")
        self.FPSSlider = QtWidgets.QSlider(Sim)
        self.FPSSlider.setGeometry(QtCore.QRect(48, 172, 160, 22))
        self.FPSSlider.setMaximum(1000)
        self.FPSSlider.setProperty("value", 60)
        self.FPSSlider.setOrientation(QtCore.Qt.Horizontal)
        self.FPSSlider.setObjectName("FPSSlider")
        self.label_4 = QtWidgets.QLabel(Sim)
        self.label_4.setGeometry(QtCore.QRect(48, 150, 165, 16))
        self.label_4.setObjectName("label_4")
        self.maxVelocitySlider = QtWidgets.QSlider(Sim)
        self.maxVelocitySlider.setGeometry(QtCore.QRect(50, 294, 160, 22))
        self.maxVelocitySlider.setMaximum(1000)
        self.maxVelocitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxVelocitySlider.setObjectName("maxVelocitySlider")
        self.label_5 = QtWidgets.QLabel(Sim)
        self.label_5.setGeometry(QtCore.QRect(50, 272, 165, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Sim)
        QtCore.QMetaObject.connectSlotsByName(Sim)

    def retranslateUi(self, Sim):
        _translate = QtCore.QCoreApplication.translate
        Sim.setWindowTitle(_translate("Sim", "Form"))
        self.label_2.setText(_translate("Sim", "Slider to change min bots"))
        self.label_3.setText(_translate("Sim", "Slider to change mutation"))
        self.label_4.setText(_translate("Sim", "FPS"))
        self.label_5.setText(_translate("Sim", "Max Velocity"))
